# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contacts
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RealmSwift'

  target 'ContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactsUITests' do
    # Pods for testing
  end

end
